name: Deploy Documentation

on:
  push:
    branches:
      - main  # O il tuo branch predefinito

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Sync Markdown Files 🔄
        run: python docs/sync_docs.py

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # La cartella che contiene il sito
          branch: gh-pages # Il branch di destinazione
